# example configuration file with snake_case keys
owner: Bob TBeam

channel_url: https://www.meshtastic.org/d/#CgUYAyIBAQ

location:
  lat: 35.88888
  lon: -93.88888
  alt: 304

user_prefs:
  region: 1
  is_always_powered: 'true'
  send_owner_interval: 2
  screen_on_secs: 31536000
  wait_bluetooth_secs: 31536000
