# example configuration file with snake_case keys
owner: Bob TBeam
owner_short: BOB

channel_url: https://www.meshtastic.org/d/#CgUYAyIBAQ

location:
  lat: 35.88888
  lon: -93.88888
  alt: 304

user_prefs:
  region: 1
  is_always_powered: 'true'
  screen_on_secs: 31536000
  wait_bluetooth_secs: 31536000
  location_share: 'LocEnabled'
canned: "What am I doing?|I'm fine|Don't follow me|I'm out|I'm back|Need helping hand|Help me with saw|I need an alpinist|I need ambulance|Keep Calm|On my way|Need 5 mins|I will be late|I'm already waiting|I couldn't join|We have company|Beer is cold|Roger"
